<a href="https://colab.research.google.com/github/darishkhan/Numerical-Linear-Algebra-Lab/blob/main/Assignment8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 8**

Name: Mohd Darish Khan

Roll No.: 2101MC29

In [ ]:
# all the necessary libraries
import numpy as np
import scipy as sp

In [ ]:
# function to calculate the dominant eigenvalue by power method (for CSR matrices)
def SelfPower_m(A, x0, maxNumIter, tol=1e-8):
  lamda = 0
  i = 0
  x_ = x0/sp.sparse.linalg.norm(x0)
  prevlamda = 1e15

  while(i < maxNumIter):
    x_ = x_.transpose()
    p = sp.sparse.csr_matrix(A.toarray()@x_.toarray())
    x_=x_.transpose()
    p_ = p/sp.sparse.linalg.norm(p)
    lamda = (x_.toarray()@p.toarray())[0,0]
    if(abs(lamda-prevlamda)<tol*abs(lamda)):
      break
    i+=1
    x_=p_.transpose()
    prevlamda = lamda
  print("Actual Iterations done = ",i)
  return lamda

In [ ]:
A = np.array([[4, -1, 0, 0, 0, 0],
              [-1, 4, -1, 0, 0, 0],
              [0, -1, 4, -1, 0, 0],
              [0, 0, -1, 4, -1, 0],
              [0, 0, 0, -1, 4, -1],
              [0, 0, 0, 0, -1, 4]])
x0 = np.random.random_sample(len(A))
A1 = sp.sparse.csr_matrix(A)
x1 = sp.sparse.csr_array(x0)
print("By our function: \n", SelfPower_m(A1, x1, 150))
print("By inbuilt eig function: \n", np.max(np.linalg.eig(A)[0]))


Actual Iterations done =  40
By our function: 
 5.801937497714188
By inbuilt eig function: 
 5.801937735804842


In [ ]:
def SelfSD_m(A, x0, b, maxNumIter, tol = 1e-8):
  x = x0
  r = b-A@x
  p=A@r
  while(maxNumIter>0):
    alpha = np.dot(r, r)/np.dot(r, p)
    x = x + alpha*r
    r = r - alpha*p
    p  = A@r
    if(np.linalg.norm(r)<tol):
      break
  return x


In [ ]:
A = np.array([[4, -1, 0, 0, 0, 0],
              [-1, 4, -1, 0, 0, 0],
              [0, -1, 4, -1, 0, 0],
              [0, 0, -1, 4, -1, 0],
              [0, 0, 0, -1, 4, -1],
              [0, 0, 0, 0, -1, 4]])
b = np.array([0,5,0,6,-2,6])
x0 = np.random.random_sample(np.shape(b))
print("The matrix A = \n", A)
print("\nThe matrix b = \n", b)
print("\nInitial random guess, x0 = \n", x0)
print("\nSolution from our Steepest Descent function: \n", SelfSD_m(A, x0, b, 150))
print("\nSolution from inbuilt direct solver: \n", np.linalg.solve(A, b))


The matrix A = 
 [[ 4 -1  0  0  0  0]
 [-1  4 -1  0  0  0]
 [ 0 -1  4 -1  0  0]
 [ 0  0 -1  4 -1  0]
 [ 0  0  0 -1  4 -1]
 [ 0  0  0  0 -1  4]]

The matrix b = 
 [ 0  5  0  6 -2  6]

Initial random guess, x0 = 
 [0.33317715 0.8388164  0.30799212 0.87419456 0.2605018  0.09579028]

Solution from our Steepest Descent function: 
 [0.38921333 1.55685331 0.83819993 1.79594641 0.34558571 1.58639643]

Solution from inbuilt direct solver: 
 [0.38921333 1.55685332 0.83819993 1.79594641 0.34558571 1.58639643]
