<a href="https://colab.research.google.com/github/darishkhan/Numerical-Linear-Algebra-Lab/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np
from sympy import *
from scipy.linalg import  lu

In [ ]:
# LU decomposition without pivoting
def luSelfnP_m(A):
  n=len(A)
  lower = np.zeros((n,n))
  upper = np.zeros((n,n))

  for i in range(n):
      for k in range(i, n):
          sum = 0
          for j in range(i):
              sum += (lower[i,j] * upper[j,k])
          upper[i,k] = A[i,k] - sum

      for k in range(i, n):
          if (i == k):
              lower[i,i] = 1
          else:
              sum = 0
              for j in range(i):
                  sum += (lower[k,j] * upper[j,i])
              lower[k,i] =((A[k,i] - sum) /upper[i,i])
  # return L and U
  return(lower, upper)

In [ ]:
# function for forward substitution
def bdSubs_m(L, b):
    n = len(L)
    ans = []
    for i in range(n-1,-1,-1):
        k = b[i]
        for j in range(n-1,i,-1):
            k -= L[i,j] * ans[n-j-1]
        ans.append(k/L[i,i])
    return np.flip(ans)

In [ ]:
# function for forward substitution
def fdSubs_m(L, b):
    ans=[]
    n = len(L)
    for i in range(n):
        k=b[i]
        for j in range(i):
            k-=L[i,j]*ans[j]
        ans.append(k/L[i,i])
    return ans

In [ ]:
#Q1.

n = 2
A = np.ones((n, n))
A[0, 0] = math.pow(10, -17)
print("A = \n", A)
b = np.array([1, 0])
L, U = luSelfnP_m(A)
# L = np.round(L, 2)
# U = np.round(U, 2)
Y = fdSubs_m(L, b)
X = bdSubs_m(U, Y)
print("By process, X = ", X)
print("By direct solver, X = ",np.linalg.solve(A, b))

A[0, 0] = math.pow(10, -10)
print("\nA = \n",A)
L, U = luSelfnP_m(A)
Y = fdSubs_m(L, b)
X = bdSubs_m(U, Y)
print("By process, X = ", X)
print("By direct solver, X = ",np.linalg.solve(A, b))

A[0, 0] = math.pow(10, -15)
print("\nA = \n",A)
L, U = luSelfnP_m(A)
Y = fdSubs_m(L, b)
X = bdSubs_m(U, Y)
print("By process, X = ", X)
print("By direct solver, X = ",np.linalg.solve(A, b))

A = 
 [[1.e-17 1.e+00]
 [1.e+00 1.e+00]]
By process, X =  [0. 1.]
By direct solver, X =  [-1.  1.]

A = 
 [[1.e-10 1.e+00]
 [1.e+00 1.e+00]]
By process, X =  [-1.00000008  1.        ]
By direct solver, X =  [-1.  1.]

A = 
 [[1.e-15 1.e+00]
 [1.e+00 1.e+00]]
By process, X =  [-1.11022302  1.        ]
By direct solver, X =  [-1.  1.]


In [ ]:
#function for LU decomposition with pivoting
def luSelfwP_m(A):
  n=len(A)
  lower = np.zeros((n,n))
  upper = np.zeros((n,n))
  pivot = np.zeros((n,n))

  # for pivoting
  for i in range(n):
    pivot[i, i]=1
  for i in range(n):
    maxv = abs(A[i, i])
    maxi = i
    for j in range(i+1, n):
      if(maxv < abs(A[j, i])):
        maxv = abs(A[j, i])
        maxi = j

    if(maxi > i):
      A[[i, maxi]] = A[[maxi, i]]
      pivot[[i, maxi]] = pivot[[maxi, i]]

  # then apply dolittle algorithm
  for i in range(n):
      for k in range(i, n):
          sum = 0
          for j in range(i):
              sum += (lower[i,j] * upper[j,k])
          upper[i,k] = A[i,k] - sum

      for k in range(i, n):
          if (i == k):
              lower[i,i] = 1
          else:
              sum = 0
              for j in range(i):
                  sum += (lower[k,j] * upper[j,i])
              lower[k,i] =((A[k,i] - sum) /upper[i,i])
  # return P, L and U
  return(pivot, lower, upper)


In [ ]:
n = 2
A = np.ones((n, n))
A[0, 0] = math.pow(10, -17)
b = np.array([1, 0])

print("By direct solver, X = ",np.linalg.solve(A, b))

P, L, U = luSelfwP_m(A)
print("\nP = \n", P)
print("L = \n", L)
print("U = \n", U)
print(np.dot(L, U))

Y = fdSubs_m(L, np.dot(P,b))
X = bdSubs_m(U, Y)
print("By process, X = ", X)


By direct solver, X =  [-1.  1.]

P = 
 [[0. 1.]
 [1. 0.]]
L = 
 [[1.e+00 0.e+00]
 [1.e-17 1.e+00]]
U = 
 [[1. 1.]
 [0. 1.]]
[[1.e+00 1.e+00]
 [1.e-17 1.e+00]]
By process, X =  [-1.  1.]


In [ ]:
#loop for i
for i in [20, 40, 60, 100]:
  print("\n")
  #generate random matrices
  A = np.random.random_sample((i, i))
  A[0,0] = math.pow(10, -20)

  L, U = luSelfnP_m(A)
  norm1 = np.linalg.norm(A - np.dot(L, U))
  print("Norm from luSelfnP_m = ", norm1)

  P, L, U = luSelfwP_m(A)
  norm2 = np.linalg.norm(np.dot(P, A) - np.dot(L, U))
  print("Norm from luSelfnP_m = ", norm2)

  P, L, U = lu(A)
  norm3 = np.linalg.norm(np.dot(P, A) - np.dot(L, U))
  print("Norm from lu function= ", norm3)



Norm from luSelfnP_m =  36111.40788526292
Norm from luSelfnP_m =  7.928337876046487
Norm from lu function=  7.230776602632638


Norm from luSelfnP_m =  69460.10693989656
Norm from luSelfnP_m =  15.961763523758957
Norm from lu function=  15.46814051895272


Norm from luSelfnP_m =  83419.38416224765
Norm from luSelfnP_m =  24.0472807909199
Norm from lu function=  23.72459404414017


Norm from luSelfnP_m =  236860.17698411376
Norm from luSelfnP_m =  40.92716886029488
Norm from lu function=  40.09137069570498


In [ ]:
#Q4.
# function for computing RREF
def rrefSelfwP_m(A):
  m, n = np.shape(A)
  i, l=0, 0
  while(i<m and l<n):
    mx=i
    mxv=abs(A[i, l])

    for j in range(i+1, m):
      if mxv<abs(A[j, i]):
        mxv = abs(A[j, i])
        mx = j

    if(mx>i):
      A[[i,mx]] = A[[mx, i]]
    if(A[i,l]==0):
      l+=1
      continue

    for j in range(i+1, m):
      mul = A[i, l]/A[j, l]
      A[j] = np.round(A[j] - (A[i]/mul), 2)

    mul = A[i, l]
    for j in range(l, n):
      A[i, j] = np.round(A[i, j]/mul , 2)
    i+=1
    l+=1
  i=1

  while(i<m):
    j=i
    while(j<n):
      if(A[i, j]==1):
        break
      j+=1
    if(j>=n):
       break
    for k in range(i-1, -1, -1):
      mul = A[i, j]/A[k, j]
      A[k] = np.round(A[k] -(A[i]/mul),2)
    i+=1

  return A


A = np.array([[ 1., 3, 3],
              [ 2, 7, 5],
              [ 3, 10, 8],
              [5, 2 , 7]])

print("Matrix is: \n", A)
print("RREF calculated by created function: \n", rrefSelfwP_m(A))

A=Matrix(A)
A = np.array(A.rref()[0])

print("RREF by .rref() command: \n", A)

Matrix is: 
 [[ 1.  3.  3.]
 [ 2.  7.  5.]
 [ 3. 10.  8.]
 [ 5.  2.  7.]]
RREF calculated by created function: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
RREF by .rref() command: 
 [[1 0 0]
 [0.0 1 0]
 [0.0 0.0 1]
 [0.0 0.0 0.0]]
