<a href="https://colab.research.google.com/github/darishkhan/Numerical-Linear-Algebra-Lab/blob/main/Assignment9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 9

Name : Mohd Darish Khan

Roll No.: 2101MC29

In [ ]:
# libraries used
import numpy as np

In [ ]:
# function to calculate the solution of Ax = b by using the minimal residual method
def SelfMR_m(A, x0, b, maxNumIter, tol=1e-8):
  x = x0
  r = b - A@x
  p = A@r
  iter = 0
  while(iter < maxNumIter):
    alpha = np.dot(r, p)/np.dot(p, p)
    x = x + alpha * r
    r = r - alpha * p
    p = A@r
    iter += 1
    if(np.linalg.norm(r)<=tol):
      break
  print("No. of iterations: ", iter)
  return x

In [ ]:
# function to calculate the solution of Ax = b by using the steepest descent method
# copied from assignment 8
def SelfSD_m(A, x0, b, maxNumIter, tol = 1e-8):
  x = x0
  r = b - A@x
  p=A@r
  iter = 0
  while(iter < maxNumIter):
    alpha = np.dot(r, r)/np.dot(r, p)
    x = x + alpha*r
    r = r - alpha*p
    p  = A@r
    iter+=1
    if(np.linalg.norm(r)<=tol):
      break
  print("No. of iterations : ", iter)
  return x

In [ ]:
A = np.array([[4, -1, 0, 0, 0, 0],
[-1, 4, -1, 0, 0, 0],
[0, -1, 4, -1, 0, 0],
[0, 0, -1, 4, -1, 0],
[0, 0, 0, -1, 4, -1],
[0, 0, 0, 0, -1, 4]])

b = np.array([0, 5, 0, 6, -2, 6])
x0 = np.random.random_sample(np.shape(b))

print("The matrix A : \n", A)
print("\nThe matrix b : ", b)
print("\nThe matrix x0 : ", x0)

print("\nBy minimum residual method : ")
print("Solution = ", SelfMR_m(A, x0, b, 150))

print("\nBy steepest descent method : ")
print("Solution = ", SelfSD_m(A, x0, b, 150))

print("\nDirect solution = ", np.linalg.solve(A, b))


# Now, we take b as an eigenvector of A and x0 = 0
print("\n\nAfter taking x0=0 and b as an eigenvector of A")
x0 = np.zeros(np.shape(b))
b = np.linalg.eig(A)[1][:,0]
print("The matrix A : \n", A)
print("\nThe matrix b : ", b)
print("\nThe matrix x0 : ", x0)

print("\nBy minimal residual method : ")
print("Solution = ", SelfMR_m(A, x0, b, 150))

print("\nBy steepest descent method : ")
print("Solution = ", SelfSD_m(A, x0, b, 150))

print("\nDirect solution = ", np.linalg.solve(A, b))

The matrix A : 
 [[ 4 -1  0  0  0  0]
 [-1  4 -1  0  0  0]
 [ 0 -1  4 -1  0  0]
 [ 0  0 -1  4 -1  0]
 [ 0  0  0 -1  4 -1]
 [ 0  0  0  0 -1  4]]

The matrix b :  [ 0  5  0  6 -2  6]

The matrix x0 :  [0.7909423  0.15241163 0.69062984 0.56173282 0.40304011 0.17492026]

By minimum residual method : 
No. of iterations:  24
Solution =  [0.38921333 1.55685331 0.83819993 1.79594641 0.34558571 1.58639643]

By steepest descent method : 
No. of iterations :  23
Solution =  [0.38921333 1.55685331 0.83819993 1.79594641 0.34558571 1.58639643]

Direct solution =  [0.38921333 1.55685332 0.83819993 1.79594641 0.34558571 1.58639643]


After taking x0=0 and b as an eigenvector of A
The matrix A : 
 [[ 4 -1  0  0  0  0]
 [-1  4 -1  0  0  0]
 [ 0 -1  4 -1  0  0]
 [ 0  0 -1  4 -1  0]
 [ 0  0  0 -1  4 -1]
 [ 0  0  0  0 -1  4]]

The matrix b :  [-0.23192061 -0.41790651 -0.52112089 -0.52112089 -0.41790651 -0.23192061]

The matrix x0 :  [0. 0. 0. 0. 0. 0.]

By minimal residual method : 
No. of iterations:  1
S

In [ ]:
# function to calculate the solution of Ax = b by using the Residual Norm Steepest descent method
def SelfRNSD_m(A, x0, b, maxNumIter, tol = 1e-8):
  x = x0
  r = b-A@x
  v = np.dot(A, r)
  iter = 0
  while(iter < maxNumIter):
    alpha = np.dot(v, v)/np.dot(A@v, A@v)
    x = x + alpha*v
    r = r - alpha * A@v
    v = np.transpose(A)@r
    if(np.linalg.norm(r)<tol):
      print("Last residual : ", r)
      break
    iter += 1
  print("No. of iterations : ", iter)
  return x

In [ ]:
A = np.array([[1, -6, 9],
              [6, 2, 3],
              [9, 3, 2]])
b = np.array([0, 5, 0])
x0 = np.random.random_sample(np.shape(b))

print("The matrix A : \n", A)
print("\nThe matrix b : ", b)
print("\nThe matrix x0 : ", x0)

print("\nBy Residual Norm Steepest Descent method : ")
print("Solution = ", SelfRNSD_m(A, x0, b, 5000))

print("\nBy minimum residual method : ")
print("Solution = ", SelfMR_m(A, x0, b, 5000))

print("\nBy steepest descent method : ")
print("Solution = ", SelfSD_m(A, x0, b, 5000))

print("\nDirect solution = ", np.linalg.solve(A, b))

The matrix A : 
 [[ 1 -6  9]
 [ 6  2  3]
 [ 9  3  2]]

The matrix b :  [0 5 0]

The matrix x0 :  [0.12454844 0.09124928 0.42410443]

By Residual Norm Steepest Descent method : 
Last residual :  [-8.25769745e-10  8.30090549e-09 -5.36145232e-09]
No. of iterations :  2282
Solution =  [-2.05263157  4.15789473  2.99999999]

By minimum residual method : 
No. of iterations:  5000
Solution =  [-0.09147747  0.44873507  0.26261334]

By steepest descent method : 
No. of iterations :  5000
Solution =  [ 2.78814226e+152 -7.14630051e+152 -1.15455736e+153]

Direct solution =  [-2.05263158  4.15789474  3.        ]
